### PR TITLE
add new-release script

### PR DESCRIPTION
**Pull request by j143**
Plan: (preliminary)

- [x] 1. create tag
- [x] 2. release build
- [x] 3. Sign artifacts
- [x] 4. Publish to nexus repo

Usage:
```sh
ASF_USERNAME=janardhan RELEASE_VERSION=2.1.0 RELEASE_TAG=rc0 NEXT_VERSION=2.2.0-SNAPSHOT GIT_EMAIL=janardhan@apache.org GIT_NAME=janardhan GIT_BRANCH=master  ./dev/new-release/create-tag.sh

```

### CODE REVIEW

**Comment by phaniarnab** [comment]
The steps are:
 - Prepare release (includes updating pom, creating tag)
 - Publish artifacts to the release staging location (SVN)
 - Publish artifacts to the maven staging location
 - Create vote
 - Repeat the above steps for every release candidate
 - After successful voting: publish to apache release location, and maven release location
 - Create python distribution (this might be part of release candidates too)
Note: This is what I roughly remember from last time. I might have missed some sub-steps.

I strongly recommend starting with the existing release scripts in the SystemDS repository.
- old-release-build.sh: prepare release
- svn_dev_upload.sh: publish to staging (SVN)
- Maven staging and release are still manual
However, the scripts are not well written, contains a lot of hard-coded locations, etc.

**Comment by j143** [comment]
Hi @phaniarnab ,

Thanks for initial review and comments.

1. I have rewritten scripts from the spark project. but a lot of WIP.
2. I am planning to add further scripts to invoke all the above steps mentioned.

   >   - Prepare release (includes updating pom, creating tag)
   >  - Publish artifacts to the release staging location (SVN)
   >  - Publish artifacts to the maven staging location
   >  - Create vote
   >  - Repeat the above steps for every release candidate
   >  - After successful voting: publish to apache release location, and maven release location
   >  - Create python distribution (this might be part of release candidates too)
   > 

3. Existing scripts are not extensible (at least for me), but already have incorporated some of the functionality.

4. > However

    > the scripts are not well written
   
    I am not unable to understand! 😕 

    > contains a lot of hard-coded locations
    
    Most of the hard-coded values are parameterized and kept in `release-utils.sh` file. and others can be parameterized as well.

**Comment by j143** [comment]
**About the review, and timeline of this project (scripts):**

My estimate is about a week to complete this project.

1. What is the release timeline planned? (like when you will create a tag, vote starting, testing etc.)
2. How are you planning to review?
    > (Are you interested in keeping a fixed schedule, something like every two days at 8:00 PM IST)

    Also, I am very much interested in real time chat at least once. (in your schedule)

3. How much effort are you interested in expending?
    > [Apache guideline for mentor](https://community.apache.org/mentoringprogramme.html#mentor)

I will take responsibility for completing the work. But, I am very much interested in how much weightage are you
planning for this project.

4. the responses in the previous comment are satisfactory?

thanks a lot,
Janardhan

**Comment by phaniarnab** [comment]
I am not really an allocate-exact-time-for-a-job and make-a-schedule-for-everything kinda guy :)
Casual chat is better for me than formal email/github reviews. You are welcome to find me on skype (live:phaniarnab_2). I am usually available there. Just ping me whenever you want to discuss something. I will generally be in touch with you throughout.

Regarding the scripts, the most difficult part is the testing. These scripts are supposed to commit, add tags and publish, which we cannot do just for practice. I encourage you to think about a way to test (on a fork, fake maven repo if possible etc.) For python distribution, TestPyPI is given for the same reason. 
The second difficult part is to make the scripts robust in terms of maven settings, local distribution location, operating system (impacts character set), etc.

As I proposed in the dev mailing list, we have a month. I suggest starting simple, one-by-one. First, write a script for the prepare release part. Check the comments in old-release-build.sh to understand the sub-steps. Then you can start from scratch if that helps. Do not overwhelm yourself with Spark or other projects' release processes, simply stick to the steps we followed in 2.0 release and focus your effort on automating. It is fine to have multiple scripts and partial automation as long as that is well documented.

Regarding the timeline, I don't think that one week is sufficient. We need the prepare release and publish scripts in a month. The final deployment (staging to release repo) scripts are only needed once the release candidates are voted. Each RC will give us a chance to test the scripts :). It is fine if the scripts are not perfectly running before RC1. 

Thanks again for your effort and let me know if this is too much for you. :)

**Pull request closed without merging**
