### PR TITLE
Updated command for the  Training and Testing the Model in standalone-guide.md in gh-pages.

### PR DESCRIPTION
**Pull request by mandadipavan**
updated runStandaloneSystemDS.sh file to systemds file and changed output file locations.

### CODE REVIEW

**Comment by j143** [comment]
@mandadipavan - This PR have some old commits!

**Comment by mandadipavan** [comment]
> @mandadipavan - This PR have some old commits!

@j143 - Actaully that command is not working. so, I updated that.

**Comment by mandadipavan** [comment]
Updated command for the Training and Testing the Model in standalone-guide.md in gh-pages.

**Comment by j143** [comment]
Not only `j143:gh-pages`, your fork should also be in `mandadipavan:gh-pages` not `mandadipavan:branch-0.10`

If you have still have some issue try to file [an issue](https://github.com/j143/systemds/issues/new)

cc @mandadipavan

**Pull request closed without merging**
